#!/usr/bin/env bash

if
  [[ -s "/root/ICanHazArtToo/.rvm/gems/ruby-2.1.3/environment" ]]
then
  source "/root/ICanHazArtToo/.rvm/gems/ruby-2.1.3/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/root/ICanHazArtToo/.rvm/gems/ruby-2.1.3/environment'" >&2
  exit 1
fi
