#!/usr/bin/env bash

if
  [[ -s "/root/ICanHazArtToo/.rvm/gems/ruby-2.1.3@global/environment" ]]
then
  source "/root/ICanHazArtToo/.rvm/gems/ruby-2.1.3@global/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/root/ICanHazArtToo/.rvm/gems/ruby-2.1.3@global/environment'" >&2
  exit 1
fi
